_format_version: "1.1"
services:
  - name: iam-service
    connect_timeout: 60000
    enabled: true
    host: iam-server-release
    path: /
    port: 8084
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - name: iam-auth
        https_redirect_status_code: 426
        methods:
          - GET
          - POST
          - DELETE
          - HEAD
          - OPTIONS
          - PUT
          - PATCH
        path_handling: v1
        paths:
          - /iam/api/v1
        plugins:
          - config:
              enable_json_header: null
              enable_permission_validate: null
              enable_raw_header: true
              enable_url_encode: null
              hosts:
                - iam-server-release:5051
              redirect_types: null
              redirect_url: null
              token_key_in_cookie: null
              verified_service: null
            enabled: true
            name: kong-auth-plugin
            protocols:
              - grpc
              - grpcs
              - http
              - https
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: false
      - name: iam-login
        https_redirect_status_code: 426
        methods:
          - POST
          - OPTIONS
        path_handling: v1
        paths:
          - /iam/api/v1/login
          - /iam/api/v1/admin/login
          - /iam/api/v1/mfa/verify
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: false
      - name: iam-no-auth
        https_redirect_status_code: 426
        methods:
          - GET
          - OPTIONS
        path_handling: v1
        paths:
          - /iam/api/v1/scopes
          - /iam/api/v1/version
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: false
      - name: no-auth-saml
        https_redirect_status_code: 426
        methods:
          - POST
          - GET
          - OPTIONS
        path_handling: v1
        paths:
          - /saml
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: false
    tags:
      - pegasus-system
    write_timeout: 60000
